server:
  port: 8765

spring:
  application:
    name: service-feign
    
eureka:
  instance:
    server: localhost
    port: 8761
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.server}:${eureka.instance.port}/eureka/
      

feign:
  hystrix: 
    enabled: true

---
spring:
  profiles: eureka-ha
eureka:
  instance:
    server: eureka1
    port:  8761
  client:
    serviceUrl:
      defaultZone: http://eureka1:8761/eureka/,http://eureka2:8760/eureka/