server:
  port: 8765

spring:
  application:
    name: service-feign
    
eureka:
  instance:
    server: localhost
    port: 8761
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.server}:${eureka.instance.port}/eureka/

feign:
  hystrix: 
    enabled: true