version: '3'
services:
  eureka-server:
    image: mydokcer/eureka-server
    restart: always
    ports:
      - 8761:8761

  service-hello:
    image: mydocker/service-hello
    restart: always
    links:
      - eureka-server:8761
    ports:
      - 8763:8763
