server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      
      
---
spring:
  profiles: eureka1
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
      serviceUrl:
        defaultZone: http://eureka2:8760/eureka/

---
spring:
  profiles: eureka2
server:
  port: 8760
eureka:
  instance:
    hostname: localhost
  client:
      serviceUrl:
        defaultZone: http://eureka2:8761/eureka/
        