server:
  port: 8769

spring:
  application:
    name: service-zuul
    
eureka:
  instance:
    server: localhost
    port:  8761
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.server}:${eureka.instance.port}/eureka/

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-ribbon
    api-b:
      path: /api-b/**
      serviceId: service-feign    

---
spring:
  profiles: eureka-ha
eureka:
  instance:
    server: eureka1
    port:  8761
  client:
    serviceUrl:
      defaultZone: http://eureka1:8761/eureka/,http://eureka2:8760/eureka/     
      