server:
  port: 8762

spring:
  application:
    name: service-hello
eureka:
  instance:
    server: localhost
    port:  8761
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.server}:${eureka.instance.port}/eureka/

---
spring:
  profiles: eureka-ha
eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaserver1:8761/eureka/,http://eurekaserver2:8761/eureka/
      
---
spring:
  profiles: docker
server:
  port: 8762
logging:
  path: /working/logs/
eureka:
  instance:
    hostname: service-hello
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
      
---
spring:
  profiles: eureka-docker-ha
server:
  port: 8763
eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaserver1:8761/eureka/,http://eurekaserver2:8761/eureka/
      
