server:
  port: 8762

spring:
  application:
    name: service-hello
eureka:
  instance:
    server: localhost
    port:  8761
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.server}:${eureka.instance.port}/eureka/

---
spring:
  profiles: eureka-ha
eureka:
  instance:
    server: eureka1
    port:  8761
  client:
    serviceUrl:
      defaultZone: http://eureka1:8761/eureka/,http://eureka2:8760/eureka/
      
