server:
  port: 8762

spring:
  application:
    name: service-hello
    
eureka:
  instance:
    server: localhost
    port:  8761
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.server}:${eureka.instance.port}/eureka/
      
