---
server:
  port: 8888
  
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          password: 
          searchPaths: respo
          uri: https://github.com/forezp/SpringcloudConfig/
          username: 
      label: master
  

