---
server:
  port: 8770

eureka:
  server:
    hostname: localhost
    port: 8761
  client:
    serviceUrl:
      defaultZone: http://${eureka.server.hostname}:${eureka.server.port}/eureka/

           
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          password: 
          searchPaths: respo
          uri: https://github.com/kevinliyq/SpringcloudConfig/
          username: 
      label: master

---
spring:
  profiles: eureka-ha
eureka:
  instance:
    server: eureka1
    port:  8761
  client:
    serviceUrl:
      defaultZone: http://eureka1:8761/eureka/,http://eureka2:8760/eureka/       

