server:
  port: 8764

spring:
  application:
    name: service-ribbon
    
eureka:
  instance:
    server: localhost
    port:  8761
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.server}:${eureka.instance.port}/eureka/
      